name: Simple CI Test

on:
  push:
    branches:
      - main

jobs:
  test-job:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello Message
        run: echo "Hello from GitHub CI"

      - name: Print Date
        run: date

      - name: Show Files
        run: ls -la
